import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import router from "./router";
import { usePinia, userStore } from "./stores";
const app = createApp(App);
usePinia(app);
userStore.restoreUserFromLocalStorage();
app.use(router);
app.mount("#app");
